-- Optional: CREATE DATABASE manually in terminal
-- CREATE DATABASE trails;

DROP TABLE IF EXISTS  trail;


CREATE TABLE trails (
    OSMPTrailsOSMPOBJECTID INTEGER,
    OSMPTrailsOSMPOWNER TEXT,
    OSMPTrailsOSMPBICYCLES TEXT,
    OSMPTrailsOSMPDISPLAY TEXT,
    OSMPTrailsOSMPTRAILTYPE TEXT,
    OSMPTrailsOSMPDATEFROM TIMESTAMPTZ,
    OSMPTrailsOSMPDATETO TIMESTAMPTZ,
    OSMPTrailsOSMPSEGMENTID TEXT,
    OSMPTrailsOSMPHORSES TEXT,
    OSMPTrailsOSMPRID INTEGER,
    OSMPTrailsOSMPLENGTH DOUBLE PRECISION,
    OSMPTrailsOSMPWIDTH TEXT,
    OSMPTrailsOSMPACCESSIBLE TEXT,
    OSMPTrailsOSMPNOTES TEXT,
    OSMPTrailsOSMPDOGS TEXT,
    OSMPTrailsOSMPNAME TEXT,
    OSMPTrailsOSMPTRAILID TEXT,
    OSMPTrailsOSMPUSE TEXT,
    OSMPTrailClosuresOBJECTID INTEGER,
    OSMPTrailClosuresTRAILID TEXT,
    OSMPTrailClosuresDATEFROM TIMESTAMPTZ,
    OSMPTrailClosuresDATETO TIMESTAMPTZ,
    OSMPTrailClosuresCLOSUREDURATION TEXT,
    OSMPTrailClosuresWEBLINK TEXT,
    OSMPTrailClosuresCLOSUREAREA TEXT,
    OSMPTrailClosuresTRAILSTATUS TEXT,
    OSMPTrailClosuresCLOSUREREASON TEXT,
    OSMPTrailClosuresLOCATIONDESCRIPTION TEXT,
    OSMPTrailClosuresCONTACT TEXT,
    OSMPTrailClosuresCOMMENTS TEXT,
    OSMPTrailClosuresGLOBALID TEXT,
    OSMPTrailClosuresSEGMENTID TEXT
);